# Generated by Django 3.0.1 on 2019-12-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_main_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductMainCategories')),
            ],
            options={
                'db_table': 'product_sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_image', models.URLField(max_length=2000, null=True)),
                ('info', models.CharField(max_length=1000, null=True)),
                ('detail_image', models.URLField(max_length=2000, null=True)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductMainCategories')),
            ],
            options={
                'db_table': 'brands',
            },
        ),
    ]
