# Generated by Django 3.0.1 on 2019-12-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_image', models.URLField(max_length=2000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
            options={
                'db_table': 'product_sub_images',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, null=True)),
                ('main_text', models.CharField(max_length=1000, null=True)),
                ('md_name', models.CharField(max_length=50, null=True)),
                ('main_image', models.URLField(max_length=2000, null=True)),
                ('new_image', models.URLField(max_length=2000, null=True)),
                ('search_image', models.URLField(max_length=2000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
    ]
