# Generated by Django 3.0.1 on 2020-01-01 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productinfo_productsubimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
            options={
                'db_table': 'product_option_titles',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_detail', models.CharField(max_length=100, null=True)),
                ('product_option_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductOptionTitles')),
            ],
            options={
                'db_table': 'product_option_details',
            },
        ),
    ]
