# Generated by Django 3.0.1 on 2020-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191228_1233'),
        ('product', '0006_auto_20200102_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='review',
            field=models.ManyToManyField(related_name='product_reviews_set', through='product.ProductReviews', to='user.Users'),
        ),
    ]
