# Generated by Django 3.0.1 on 2020-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200102_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptiondetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
