# Generated by Django 3.0.1 on 2019-12-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
